<template><div><h1 id="تعلم-django" tabindex="-1"><a class="header-anchor" href="#تعلم-django"><span>تعلم Django</span></a></h1>
<h2 id="api-إنشاء-العناصر-المراية-و-طريقة-العرض-و-الفلاتر" tabindex="-1"><a class="header-anchor" href="#api-إنشاء-العناصر-المراية-و-طريقة-العرض-و-الفلاتر"><span>Api =&gt; إنشاء العناصر المراية و طريقة العرض و الفلاتر</span></a></h2>
<h3 id="" tabindex="-1"><a class="header-anchor" href="#"><span></span></a></h3>
<div style="font-size:1.2vw; padding: 2rem 0 0 0; font-weight: 900;">
</div>
<div dir="rtl" style="font-size:1.2vw; padding: 1rem 0; font-weight: 900;">
</div>
<div class="language-python line-numbers-mode" data-highlighter="prismjs" data-ext="py" data-title="py"><pre v-pre><code><span class="line"><span class="token decorator annotation punctuation">@api_view</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token string">"GET"</span><span class="token punctuation">]</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token decorator annotation punctuation">@authentication_classes</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">)</span>  <span class="token comment"># 🔓 عدم استخدام مصادقة</span></span>
<span class="line"><span class="token decorator annotation punctuation">@permission_classes</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">)</span>  <span class="token comment"># 🔓 عدم استخدام تصاريح</span></span>
<span class="line"><span class="token keyword">def</span> <span class="token function">categories_list</span><span class="token punctuation">(</span>request<span class="token punctuation">)</span><span class="token punctuation">:</span>  <span class="token comment"># 🏷️ دالة لجلب جميع الفئات</span></span>
<span class="line">    categories <span class="token operator">=</span> Category<span class="token punctuation">.</span>objects<span class="token punctuation">.</span><span class="token builtin">all</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token comment"># 📚 جلب كل الفئات</span></span>
<span class="line">    serializer <span class="token operator">=</span> CategorySerializer<span class="token punctuation">(</span>categories<span class="token punctuation">,</span> many<span class="token operator">=</span><span class="token boolean">True</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token keyword">return</span> Response<span class="token punctuation">(</span>serializer<span class="token punctuation">.</span>data<span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-python line-numbers-mode" data-highlighter="prismjs" data-ext="py" data-title="py"><pre v-pre><code><span class="line"><span class="token decorator annotation punctuation">@api_view</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token string">"GET"</span><span class="token punctuation">]</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token decorator annotation punctuation">@authentication_classes</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">)</span>  <span class="token comment"># 🔓 عدم استخدام مصادقة</span></span>
<span class="line"><span class="token decorator annotation punctuation">@permission_classes</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">)</span>  <span class="token comment"># 🔓 عدم استخدام تصاريح</span></span>
<span class="line"><span class="token keyword">def</span> <span class="token function">courses_list</span><span class="token punctuation">(</span>request<span class="token punctuation">)</span><span class="token punctuation">:</span> <span class="token comment"># 🏷️ دالة لجلب جميع الكرسات</span></span>
<span class="line">    courses <span class="token operator">=</span> Course<span class="token punctuation">.</span>objects<span class="token punctuation">.</span><span class="token builtin">all</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token comment"># 📚 جلب كل الكرسات</span></span>
<span class="line">    serializer <span class="token operator">=</span> CourseListSerializer<span class="token punctuation">(</span>courses<span class="token punctuation">,</span> many<span class="token operator">=</span><span class="token boolean">True</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token keyword">return</span> JsonResponse<span class="token punctuation">(</span>serializer<span class="token punctuation">.</span>data<span class="token punctuation">,</span> safe<span class="token operator">=</span><span class="token boolean">False</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


